spring:
  datasource:
    url: jdbc:mysql://47.100.168.157:3306/house
    username: root
    password: Say@59121
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      min-idle: 5
      max-active: 20
      initial-size: 5
      max-wait: 6000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall
  security:
    user:
      name: root
      password: root
  main:
    allow-bean-definition-overriding: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.house.hotel.dao.entity
  configuration:
    map-underscore-to-camel-case: true

server:
  servlet:
    context-path: /hotel-api
  port: 8098
logging:
  level:
    com:
      house:
        hotel:
          dao:  debug
    org:
      springframework:
        security: debug
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mySecret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)
  tokenHead: Bearer  #JWT负载中拿到开头